// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeApp.DataAccess.Sql.Context;

#nullable disable

namespace ResumeApp.DataAccess.Sql.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20221205061411_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.CertificationSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0a5c173-10e6-4fa6-91c4-8c31adcb0c34"),
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "Azure Solutions Architect Expert",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            VerificationUrl = "https://www.credly.com/badges/42f9be70-0b40-4bb0-8256-bd9d573e36af/public_url"
                        },
                        new
                        {
                            Id = new Guid("85ad96eb-09d9-49ff-9f43-03ba5ee9bbc2"),
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Google",
                            Name = "Professional Cloud Architect",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            VerificationUrl = "https://www.credential.net/786961ad-0225-4bb0-883a-3c2feceb5174"
                        },
                        new
                        {
                            Id = new Guid("8a1079de-f850-47e5-9ffd-2bd42609e2d5"),
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Amazon",
                            Name = "AWS Certified Solutions Architect Associate",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            VerificationUrl = "https://www.credly.com/badges/dc95ff2a-12d8-4816-91b2-a9292ae5df85/public_url"
                        },
                        new
                        {
                            Id = new Guid("a96937f6-9a00-44c8-a216-de6858efed75"),
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "DevOps Engineer Expert",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            VerificationUrl = "https://www.credly.com/badges/2d29613e-7c7e-481d-aba3-842b409fecd7/public_url"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ContactSqlEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ResumeId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Key = "Location",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "Sunnyvale, CA, 94085"
                        },
                        new
                        {
                            Key = "Phone",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "+1(408)480-3600"
                        },
                        new
                        {
                            Key = "Email",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "mickey.krasilnikov@gmail.com"
                        },
                        new
                        {
                            Key = "Accredible",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "https://www.credential.net/profile/mikhailkrasilnikov328966/wallet"
                        },
                        new
                        {
                            Key = "Credly",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "https://www.credly.com/users/mickey-krasilnikov/badges"
                        },
                        new
                        {
                            Key = "LinkedIn",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            Value = "https://www.linkedin.com/in/mickeykrasilnikov/"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.EducationSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c60ecfd2-bd9a-4aba-8b41-7235c78cec03"),
                            Degree = "Bachelor's degree",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Design and technology of radio electronic devices",
                            Name = "Penza State University",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://international.pnzgu.ru/"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrentCompany")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e7b2051-8774-47c3-b826-7d7dfb34bf6d"),
                            Company = "EPAM Systems",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lead Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("ebae285d-cde6-4cc6-a4d0-fd40966bf331"),
                            Company = "Credit Suisse",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Front Office Risk System Developer (AVP) (Senior Software Engineer)"
                        },
                        new
                        {
                            Id = new Guid("30509bff-4c5d-41f0-ae29-852b51dd07b2"),
                            Company = "SINTEGRO SOFT",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("88ddacf2-141f-4f28-9740-7f4477eb5cf2"),
                            Company = "Gollard",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("9ef842b2-26e0-47db-9906-45bf5c9aa12d"),
                            Company = "SGC",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("126533a6-23c5-4fd8-8c9c-f332e2da0173"),
                            Company = "Research and Production Center 'Start'",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrentCompany = false,
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ProjectSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrentProject")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TaskPerformed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb2bd704-e700-4d53-b666-4d239f184ac5"),
                            Client = "Broadridge",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET Core 6.0, Vue.js, Python 3.7, AWS, AWS Lambda, AWS S3, AWS Beanstalk, AWS EC2, AWS Code Commit, AWS Code Build, AWS Code Deploy, AWS Code Pipeline, Docker, AWS RDS, GIT",
                            ExperienceId = new Guid("9e7b2051-8774-47c3-b826-7d7dfb34bf6d"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer, Team Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("83c9f60f-673e-4e80-9e9c-b65f6a34fee2"),
                            Client = "ElipsLife",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET Core 6.0Angular 13Go LangAzureAzure DevOpsOctopusOKTADockerCosmos DBRedisMS SQLGIT",
                            ExperienceId = new Guid("9e7b2051-8774-47c3-b826-7d7dfb34bf6d"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer, Team Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Designed microservice-based hybrid-cloud solution architecture for multi-role self-service portal for managing insurance claims + underwriting + and broker reports.Designed and developed microservices following a RESTful approach and applying best practices. • Covered code with unit and contract tests and maintained code coverage on 80%.Configured CI/CD pipelines and established automated quality gates on different stages.Mentored new joiners and supported them during the ramp-up period.Performed systematic knowledge transfer to the client support team + including the creation of visual documentation. Introduced and ensured the development team follows the very best engineering practices (with respect to various limitations on the client side)."
                        },
                        new
                        {
                            Id = new Guid("82f125db-50d1-499b-a00d-96a953d96918"),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET Core 2.1, .NET 4.6, WPF, WCF, EF, MS SQL, MS SSAS, TeamCity, Jira, Confluence, Splunk, GIT",
                            ExperienceId = new Guid("ebae285d-cde6-4cc6-a4d0-fd40966bf331"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer, Tech Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Maintained Risk Management System for Credit Suisse Front Office and developed new modules. Improved performance and decreased memory usage in CS in-house distributed cache. Splatted monolith server-side architecture to microservices. Analyzed and arranged requirements with traders + BAU team and QA. Supported worldwide users as a part of the SL3 team. Administrated CI/CD on TeamCity. Documented design decisions and usage examples. Mentored new joiners."
                        },
                        new
                        {
                            Id = new Guid("beddb152-6ad7-4f70-b554-7a72e04227fd"),
                            Client = "Yandex",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET 4.5, ASP.NET MVC 5, ASP.NET Web API, WPF, MS SQL, EF, TFS, WIX, GIT",
                            ExperienceId = new Guid("30509bff-4c5d-41f0-ae29-852b51dd07b2"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Participated in the development of the system that helps organize corporate bonuses + such as meals + mobile phones + fitness + transportation + etc.Developed user personal page that contains account balance and transaction history. Developed desktop administration systems for corporate bonus managers.Documented design decisions + component APIs and usage examples.Participated in the software integration process."
                        },
                        new
                        {
                            Id = new Guid("39e39a57-b90e-4ca9-8724-2e103e5fe35f"),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET 4.5, WPF, WCF, ASP.NET Web API, Esri ArcGIS, MS SQL, MySQL, GitLab, WIX, GIT",
                            ExperienceId = new Guid("88ddacf2-141f-4f28-9740-7f4477eb5cf2"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Participated in the development of desktop GIS application for the power distribution company dealing with electrical grids, stations and facilities on the map.Implemented a feature that allows monitoring the service transport on the map in real-timeIntroduced the possibility to view video streams from the cameras marked on the map.Participated in the development of the solution to maintain security and safety of the buildings and areas using cameras and different types of sensors.Implemented an alerting system that works based on the biometric data from the cameras or events from the sensors."
                        },
                        new
                        {
                            Id = new Guid("4f7ba226-dca3-4f6a-8587-ebceef364b7d"),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET 4.0, WPF, SOAP, MS SQL, WIX, SVN",
                            ExperienceId = new Guid("9ef842b2-26e0-47db-9906-45bf5c9aa12d"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed software for composing estimates to determine the cost of construction.Integrated with other well-known systems available on the market for composing estimates."
                        },
                        new
                        {
                            Id = new Guid("86f3fb29-4dd8-4696-8fc6-7a90d64736ce"),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Environment = ".NET 3.5, WinForms, SOAP, MS SQL, SVN",
                            ExperienceId = new Guid("126533a6-23c5-4fd8-8c9c-f332e2da0173"),
                            IsCurrentProject = false,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed software for designing micro boards and creating a mask for interacting with third-party equipment for printing this kind of product."
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            FirstName = "Mikhail",
                            LastName = "Krasilnikov",
                            Summary = "12+ years of professional programming experience with consistently increasing responsibilities in the design and development of commercial applications on different platforms and environments \nCertified Cloud Solution Architect (Azure, GCP, AWS) \nExperienced as a Team Leader \nInvolved in full Software Development Life Cycle (SDLC)",
                            Title = "Lead Software Engineer"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb571259-c6bd-4425-b4b8-1e44261ef599"),
                            AdditionalInfo = ".Net Core, .Net",
                            Name = "C#",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = new Guid("87b0c15c-b4a5-41e4-9346-c5fdeba4affa"),
                            AdditionalInfo = "Gin",
                            Name = "GoLang",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = new Guid("91968550-e11e-45b1-bd35-e628c6898214"),
                            AdditionalInfo = "Node.js",
                            Name = "Javascript",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = new Guid("088736fb-df50-4fc3-a131-c92c23192969"),
                            AdditionalInfo = "FastAPI",
                            Name = "Python",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = new Guid("4bda5608-4160-4a65-a874-b672b248cd1f"),
                            Name = "Angular",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("280e6565-d075-418b-ad16-f354c426d5e4"),
                            Name = "Vue.js",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("41e824af-bcaf-40c9-9884-ede94b0dcfec"),
                            Name = "JavaScript",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("1e673657-545a-477b-92cc-e2b2c99d72f5"),
                            Name = "TypeScript",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("e04fd530-1420-43bd-9e16-42be22d6ff29"),
                            Name = "HTML",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("d9dbe63f-09c8-48ea-b87b-989aa5f3cdc6"),
                            Name = "CSS",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = new Guid("d7951bcb-29b0-44f2-a044-3f48e70a4ab1"),
                            AdditionalInfo = "MS SQL",
                            Name = "T-SQL",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = new Guid("9e48dff5-2bde-4d84-bbec-ea8e5c10f5e0"),
                            AdditionalInfo = "MySQL",
                            Name = "SQL/PSM",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = new Guid("1a5e5d9d-3d21-42fd-96e7-84fa8cca13fa"),
                            AdditionalInfo = "PostgreSQL, Oracle",
                            Name = "PL-SQL",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = new Guid("669e70e0-4a36-4864-8a7c-31dc78c1fa94"),
                            Name = "MongoDB",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = new Guid("6bedf9e7-625d-454c-b51e-35871fc2fbe8"),
                            Name = "Redis",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = new Guid("9d808f6e-92be-4acf-95c3-d89c66d4af36"),
                            Name = "CosmosDB",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = new Guid("9f7db796-8d0b-4c9d-a50d-5535273dafc1"),
                            Name = "DynamoDB",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = new Guid("45b62247-f738-48f6-8339-c0c8e57f6eb5"),
                            Name = "BigTable",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = new Guid("b2f4335f-3ff6-4ba8-8144-4d9d89fb42e2"),
                            Name = "Docker",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = new Guid("1467bc6b-d0b2-451c-8640-be2c06c1aa05"),
                            Name = "Docker Swarm",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = new Guid("32bdb763-b939-4d4c-a266-6dc9d2a60b06"),
                            Name = "Kubernetes",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = new Guid("7b3fe737-ee87-4939-9d24-13f50b6956c5"),
                            Name = "Azure DevOps",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("363c11a3-df91-489c-ab75-50c2d69cf3a0"),
                            Name = "GitHub Actions",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("a1102dc4-d1af-4e78-be19-7a2f20bb77b6"),
                            Name = "AWS CodePipeline",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("9170bfed-4b5c-4583-aacc-c596324249cd"),
                            Name = "Octopus",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("70bf6a37-9cec-4554-824c-08b66e6650c6"),
                            Name = "Jenkins",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("4106fd00-8048-460e-8f1d-cf47d38042d5"),
                            Name = "TeamCity",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("19bbef85-71ee-414d-beee-acc6eb18f10f"),
                            Name = "JIRA",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Bug Tracking"
                        },
                        new
                        {
                            Id = new Guid("eca45e48-2c5c-4edb-8349-60282302d68c"),
                            Name = "Azure DevOps",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Bug Tracking"
                        },
                        new
                        {
                            Id = new Guid("ad9f085b-2675-4bce-be22-f6158130b734"),
                            Name = "GIT",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Source Control"
                        },
                        new
                        {
                            Id = new Guid("91a03baa-03c4-4d53-8e75-f555ff64ee6b"),
                            Name = "SVN",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Source Control"
                        },
                        new
                        {
                            Id = new Guid("d7833db0-6942-435b-a0c8-97a6beaccbe2"),
                            Name = "Windows",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = new Guid("5d2b12df-fee4-48fa-afde-07f5d841674e"),
                            Name = "MacOS",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = new Guid("1128cef7-65ba-4699-b917-dedb135713d6"),
                            Name = "Ubuntu",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = new Guid("1ca6a89f-b808-4d6e-adfc-90509c750c45"),
                            Name = "Azure",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("73200eac-f79b-4a68-abd7-785bc9b4c42b"),
                            Name = "AWS",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("acda6dfa-e4f5-4c6a-9a9f-e43d36925eb7"),
                            Name = "GCP",
                            ResumeId = new Guid("84b91e21-e998-464e-b8ba-c6be6c16b3be"),
                            SkillGroup = "Cloud"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.CertificationSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Certifications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ContactSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Contacts")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.EducationSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Education")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Experience")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ProjectSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", "Experience")
                        .WithMany("Projects")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
