// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeApp.DataAccess.Sql.Context;

#nullable disable

namespace ResumeApp.DataAccess.Sql.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230301090820_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.CertificationSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("521f1124-2dc6-41ef-862a-0eee1b59e4c3"),
                            ExpirationDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "Azure Solutions Architect Expert",
                            VerificationUrl = "https://www.credly.com/badges/8ea21901-34c7-4cb4-bc48-71e0c5cf3e85"
                        },
                        new
                        {
                            Id = new Guid("1b6604b4-d3e7-4073-9db6-e352dfc37757"),
                            ExpirationDate = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Google",
                            Name = "Professional Cloud Architect",
                            VerificationUrl = "https://www.credential.net/786961ad-0225-4bb0-883a-3c2feceb5174"
                        },
                        new
                        {
                            Id = new Guid("625d45d1-0135-4086-aad6-7f836cba36e1"),
                            ExpirationDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Amazon",
                            Name = "AWS Certified Solutions Architect Associate",
                            VerificationUrl = "https://www.credly.com/badges/dc95ff2a-12d8-4816-91b2-a9292ae5df85"
                        },
                        new
                        {
                            Id = new Guid("488f11c3-2b89-453b-93d6-0bcdbe1e2851"),
                            ExpirationDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "DevOps Engineer Expert",
                            VerificationUrl = "https://www.credly.com/badges/eaedb35f-5ea9-45b2-b551-acad69b94488"
                        },
                        new
                        {
                            Id = new Guid("806000d1-d1f0-495f-8498-73e58af70027"),
                            ExpirationDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "Azure Developer Associate",
                            VerificationUrl = "https://www.credly.com/badges/49ab14ad-ffe5-47ae-b3d1-9d29b00ef4dc"
                        },
                        new
                        {
                            Id = new Guid("87ca393b-4e8f-4eb6-9a84-55286fabeed6"),
                            ExpirationDate = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2020, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Google",
                            Name = "Associate Cloud Engineer",
                            VerificationUrl = "https://www.credential.net/f4054913-d10c-4cd4-89cb-e286f00de2ae"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ContactSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("[Key] IS NOT NULL");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e0076ab-34cc-4702-a9dd-26b70dfcca71"),
                            Key = "phone",
                            Link = "tel:+14084803600",
                            Value = "+14084803600"
                        },
                        new
                        {
                            Id = new Guid("f7210666-4526-4324-aee7-ae40ea9552a9"),
                            Key = "telegram",
                            Link = "https://t.me/+14084803600",
                            Value = "Telegram"
                        },
                        new
                        {
                            Id = new Guid("d0af11d2-c3ca-49a1-a105-d71dd53fbac0"),
                            Key = "whatsapp",
                            Link = "https://wa.me/+14084803600",
                            Value = "Whatsapp"
                        },
                        new
                        {
                            Id = new Guid("df973f56-bd70-4b41-8110-933ce7966bf2"),
                            Key = "email",
                            Link = "mailto:your_email",
                            Value = "Mickey.Krasilnikov@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("8ce4a50a-3fb9-4923-9eb6-e866af138a27"),
                            Key = "location",
                            Link = "https://www.google.com/maps/place/Sunyvale%20CA%2094085/",
                            Value = "Sunyvale, CA, 94085"
                        },
                        new
                        {
                            Id = new Guid("be4e59a9-52b6-42a9-b09a-d88a7eaa801b"),
                            Key = "github",
                            Link = "https://github.com/mickey-krasilnikov",
                            Value = "@mickey-krasilnikov"
                        },
                        new
                        {
                            Id = new Guid("a9028523-6999-4f8c-b9f5-6bbb371b11c9"),
                            Key = "linkedIn",
                            Link = "https://www.linkedin.com/in/mickeykrasilnikov",
                            Value = "@mickeykrasilnikov"
                        },
                        new
                        {
                            Id = new Guid("9ea39ee0-cd93-4c82-8fa3-06c301d3b7ab"),
                            Key = "accredible",
                            Link = "https://www.credential.net/profile/mikhailkrasilnikov328966/wallet",
                            Value = "@mikhailkrasilnikov328966"
                        },
                        new
                        {
                            Id = new Guid("52d23e7b-8078-434a-8045-535e9420effd"),
                            Key = "credly",
                            Link = "https://www.credly.com/users/mickey-krasilnikov/badges",
                            Value = "@mickey-krasilnikov"
                        },
                        new
                        {
                            Id = new Guid("75c5c94b-d830-486f-9a8d-9e771f5c0239"),
                            Key = "instagram",
                            Link = "https://www.instagram.com/mickey.krasilnikov",
                            Value = "@mickey.krasilnikov"
                        },
                        new
                        {
                            Id = new Guid("e2ae7016-b312-4738-acc5-79850a69deb2"),
                            Key = "facebook",
                            Link = "https://www.facebook.com/mickey.krasilnikov",
                            Value = "@mickey.krasilnikov"
                        },
                        new
                        {
                            Id = new Guid("0f1c366e-54ff-43e0-ba89-7c5409caf466"),
                            Key = "twitter",
                            Link = "https://twitter.com/mickey_kras",
                            Value = "@mickey_kras"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.EducationSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5cb0d98-3657-4890-87df-4a6b0acb839c"),
                            Degree = "Bachelor's degree",
                            EndDate = new DateTime(2013, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Design and technology of radio electronic devices",
                            Name = "Penza State University",
                            StartDate = new DateTime(2006, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://international.pnzgu.ru/"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TaskPerformed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5"),
                            Company = "EPAM Systems",
                            Location = "San Jose, CA, USA",
                            StartDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Created Execution Compliance and Trade Surveillance System for analysis of trading activities to ensure regulatory compliance.\nEngineered a Vue.js-based web dashboard for monitoring, analyzing, and visualizing data.\nDesigned and developed high-performance .NET Core backend services, resulting in a scalable and maintainable architecture.\nImplemented an event-driven workflow that utilized Amazon SQS and AWS Lambdas, written in Python, to efficiently load and parse large data files, reducing processing times and increasing overall system throughput.\n",
                            Title = "Lead Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db"),
                            Company = "EPAM Systems",
                            EndDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Wroclaw, Poland",
                            StartDate = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Designed and developed a cloud-native microservice-based system for managing insurance claims, underwriting, and reporting.\nCreated an intuitive self-service portal using Angular, improving customer satisfaction while reducing customer support inquiries.\nDeveloped highly scalable and reliable RESTful microservices in .NET Core, resulting in improved efficiency and cost savings.\nImplemented performance-critical internal services using GoLang, resulting in faster and more accurate claims processing.\nEnsured high software quality with 80% code coverage and automated quality gates in CI/CD, reducing maintenance costs.\n",
                            Title = "Lead Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da"),
                            Company = "Credit Suisse",
                            EndDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Wroclaw, Poland",
                            StartDate = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Created a high-performing desktop application for Credit Suisse's front office to manage market risks in real time using WPF and C#.\nRestructured an existing monolithic architecture into microservices, providing more flexibility and scalability while improving performance.\nImplemented automated testing, reducing the likelihood of bugs and errors and increasing the overall reliability of the system.\nOptimized the performance of the in-house distributed cache, leading to faster processing times and greater efficiency in C#.\n",
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b"),
                            Company = "Yandex",
                            EndDate = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Moscow, Russia",
                            StartDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed a payment system that streamlined the process of paying for lunch at nearby cafes and restaurants using the office access card (RFID tag), resulting in improved efficiency and convenience for employees.\nDesigned and developed a user-friendly personal page for employees, enabling them to view their transaction history and account balance.\nCreated a desktop application for administrators that simplified the process of managing employee accounts and generating reports.\n",
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8"),
                            Company = "Gollard",
                            EndDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Moscow, Russia",
                            StartDate = new DateTime(2013, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Created a GIS desktop app for energy distribution company handling grids, stations, and facilities, improving overall operational efficiency.\nEnabled real-time tracking of service transport location and engine state, enhancing the company's logistical capabilities.\nImplemented an alerting system that utilizes biometric camera data and sensor events, increasing the company's security posture.\n",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558"),
                            Company = "SGC",
                            EndDate = new DateTime(2013, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Moscow, Russia",
                            StartDate = new DateTime(2012, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed software that composes accurate construction cost estimates, which resulted in a 25% reduction in estimate preparation time.\nImproved software flexibility and saved valuable time by adding the ability to convert estimates from other well-known systems.\nStreamlined report creation process by enabling final estimate result export to various formats, providing customization options for users.\n",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("51baeba6-a565-4887-8ba4-4754a1d2a5d1"),
                            Company = "Research and Production Center 'Start'",
                            EndDate = new DateTime(2012, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Penza, Russia",
                            StartDate = new DateTime(2010, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed an in-house CAD tool for designing microboards, including the ability to import AutoCAD files.\nImplemented a feature that enables the printing of photomasks for microboards using specialized equipment.\nOptimized the CAD tool for faster and more efficient microboard design, resulting in a 30% reduction in design time.\n",
                            Title = "Software Engineer"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillExperienceMappingSqlEntity", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SkillId", "ExperienceId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("SkillExperienceMappings");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("1dc5e010-6f0e-4651-a6e0-7e7061d6c781"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("6730c197-4fde-452d-a2e2-1e9b93e82872"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("2fd77f7a-4f3e-4ba6-a1af-2ab1628471a6"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("0d007ad4-4379-4e5e-aa12-40c62927998c"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("36f830dc-864f-45bd-a567-ff35d34aa403"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("e187b2ef-0a5d-4f5c-bd42-c288b0484bce"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("bb99c612-e5e2-43c6-a8f6-4a8bc82fa47a"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("e73e86d9-8c82-4aa8-87f5-29007d4842a0"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("faedd3e4-ac78-455f-a2a6-8787cc5d2724"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("96eef699-0493-4389-8508-e0e5ac7a10ff"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("0f16ede3-0bc2-47b2-8a98-4b348f4b8202"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("014d3588-b7d8-40a9-af5e-dfc15c339c85"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("db5b7c7c-e7d7-4b4a-8462-28bbc6ce2a2c"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("1f71b23e-6eb8-444b-945f-04dc3b6e6dcc"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            ExperienceId = new Guid("bdc4ad5c-646f-4e79-9466-f77bac4bf6f5")
                        },
                        new
                        {
                            SkillId = new Guid("66721da3-eef3-4fb0-94ab-1ddd99814606"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("6730c197-4fde-452d-a2e2-1e9b93e82872"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("2fd77f7a-4f3e-4ba6-a1af-2ab1628471a6"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("a079055b-d4b7-4b96-afc3-7cb503e7e76e"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("81786180-7ffc-4d9e-a3e1-812acf9ed04b"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("4087555e-8e8c-474b-8970-62b0149ed194"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("d61e2f58-e592-4550-aad3-14b2da1abe5c"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("918a79ca-a2ec-4878-9d3f-802c4bd10a64"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("e73e86d9-8c82-4aa8-87f5-29007d4842a0"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("bb99c612-e5e2-43c6-a8f6-4a8bc82fa47a"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("faedd3e4-ac78-455f-a2a6-8787cc5d2724"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("96eef699-0493-4389-8508-e0e5ac7a10ff"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("5205ec9e-f063-45cb-a587-21bca1a74892"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("f2a2aa0c-46d2-4500-aae5-f85f93327eb8"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("e370472b-07c1-441f-8161-2c9ad7ed921b"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("1d205562-0906-4fa3-b410-1994000b8b91"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            ExperienceId = new Guid("c22a7471-6c35-42c2-9def-6fa83a0df8db")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("6730c197-4fde-452d-a2e2-1e9b93e82872"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("53065d38-ae20-4130-a2de-5dad4d7ab317"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("19a964ee-362a-4f52-82c7-901ec92b190d"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("4bc1fa9d-d2f2-4aa2-a3fb-1d7760106726"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("2d7e5810-b437-49b5-9801-9d57b1bd0c2f"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("4087555e-8e8c-474b-8970-62b0149ed194"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("16f6207a-e38c-4fa5-967d-4d4e1fd330dd"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("36f830dc-864f-45bd-a567-ff35d34aa403"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("c329e836-2e60-47ed-bcca-0e8b2b3cbef0"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("1f71b23e-6eb8-444b-945f-04dc3b6e6dcc"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            ExperienceId = new Guid("feb5ed7e-8df7-4da3-8d86-83499d25d6da")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("7c4cc9e6-deb5-41e7-85d5-f32ed2d5f771"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("16f6207a-e38c-4fa5-967d-4d4e1fd330dd"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("36f830dc-864f-45bd-a567-ff35d34aa403"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("494ed162-b23f-4ef3-a97f-3f6770ed821e"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("bb99c612-e5e2-43c6-a8f6-4a8bc82fa47a"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("faedd3e4-ac78-455f-a2a6-8787cc5d2724"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("96eef699-0493-4389-8508-e0e5ac7a10ff"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("19a964ee-362a-4f52-82c7-901ec92b190d"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("4bc1fa9d-d2f2-4aa2-a3fb-1d7760106726"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("c329e836-2e60-47ed-bcca-0e8b2b3cbef0"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            ExperienceId = new Guid("540881aa-5796-4a06-8c78-c6e80179ab5b")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("7c4cc9e6-deb5-41e7-85d5-f32ed2d5f771"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("53065d38-ae20-4130-a2de-5dad4d7ab317"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("36f830dc-864f-45bd-a567-ff35d34aa403"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("19a964ee-362a-4f52-82c7-901ec92b190d"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("4bc1fa9d-d2f2-4aa2-a3fb-1d7760106726"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("0f16ede3-0bc2-47b2-8a98-4b348f4b8202"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("a120ba72-3a02-47b0-b626-dc37208d0747"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("c329e836-2e60-47ed-bcca-0e8b2b3cbef0"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            ExperienceId = new Guid("55181ac6-56a8-47ed-90b2-86ca0d83c7b8")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("99f1aca2-fcf3-42be-a7c9-62c84f54b02e"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("19a964ee-362a-4f52-82c7-901ec92b190d"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("4bc1fa9d-d2f2-4aa2-a3fb-1d7760106726"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            ExperienceId = new Guid("1ac11019-b63f-43d8-b9cb-22ac33aa1558")
                        },
                        new
                        {
                            SkillId = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            ExperienceId = new Guid("51baeba6-a565-4887-8ba4-4754a1d2a5d1")
                        },
                        new
                        {
                            SkillId = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            ExperienceId = new Guid("51baeba6-a565-4887-8ba4-4754a1d2a5d1")
                        },
                        new
                        {
                            SkillId = new Guid("3c071533-0266-4ec6-bc24-5e38f4a26bb5"),
                            ExperienceId = new Guid("51baeba6-a565-4887-8ba4-4754a1d2a5d1")
                        },
                        new
                        {
                            SkillId = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            ExperienceId = new Guid("51baeba6-a565-4887-8ba4-4754a1d2a5d1")
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SkillGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66721da3-eef3-4fb0-94ab-1ddd99814606"),
                            IsHighlighted = true,
                            Name = "Azure",
                            Priority = 101,
                            SkillGroup = "Clouds"
                        },
                        new
                        {
                            Id = new Guid("1dc5e010-6f0e-4651-a6e0-7e7061d6c781"),
                            IsHighlighted = true,
                            Name = "AWS",
                            Priority = 102,
                            SkillGroup = "Clouds"
                        },
                        new
                        {
                            Id = new Guid("447457f9-4a41-4e58-9b24-718e171b965d"),
                            IsHighlighted = true,
                            Name = "GCP",
                            Priority = 103,
                            SkillGroup = "Clouds"
                        },
                        new
                        {
                            Id = new Guid("f6fc53fe-eac7-41c0-a278-062b77a10809"),
                            IsHighlighted = true,
                            Name = "C#",
                            Priority = 201,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("25f84d31-59d4-41af-bba4-4a96bd67e373"),
                            IsHighlighted = true,
                            Name = ".NET",
                            Priority = 203,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("6730c197-4fde-452d-a2e2-1e9b93e82872"),
                            IsHighlighted = true,
                            Name = ".NET Core",
                            Priority = 202,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("2fd77f7a-4f3e-4ba6-a1af-2ab1628471a6"),
                            IsHighlighted = true,
                            Name = "ASP.NET Core Web API",
                            Priority = 204,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("7c4cc9e6-deb5-41e7-85d5-f32ed2d5f771"),
                            IsHighlighted = true,
                            Name = "ASP.NET Web API",
                            Priority = 205,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("22135820-bfc4-4f17-b0f2-8cbdba10a2a9"),
                            IsHighlighted = true,
                            Name = "Node.js",
                            Priority = 206,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("27d65041-3a7b-4443-af7c-7ff20a0cff11"),
                            IsHighlighted = true,
                            Name = "Express.js Web Framework",
                            Priority = 207,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("a079055b-d4b7-4b96-afc3-7cb503e7e76e"),
                            IsHighlighted = true,
                            Name = "GoLang",
                            Priority = 208,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("81786180-7ffc-4d9e-a3e1-812acf9ed04b"),
                            IsHighlighted = true,
                            Name = "Gin Web Framework",
                            Priority = 209,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("0d007ad4-4379-4e5e-aa12-40c62927998c"),
                            IsHighlighted = true,
                            Name = "Python3",
                            Priority = 210,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("3978f616-4c26-43ea-953f-84c62279106e"),
                            IsHighlighted = true,
                            Name = "Flask Web Framework",
                            Priority = 211,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("53065d38-ae20-4130-a2de-5dad4d7ab317"),
                            IsHighlighted = false,
                            Name = "WCF",
                            Priority = 212,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("16f6207a-e38c-4fa5-967d-4d4e1fd330dd"),
                            IsHighlighted = false,
                            Name = "Entity Framework",
                            Priority = 213,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("4087555e-8e8c-474b-8970-62b0149ed194"),
                            IsHighlighted = false,
                            Name = "Entity Framework Core",
                            Priority = 214,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("d61e2f58-e592-4550-aad3-14b2da1abe5c"),
                            IsHighlighted = false,
                            Name = "xUnit",
                            Priority = 215,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("36f830dc-864f-45bd-a567-ff35d34aa403"),
                            IsHighlighted = false,
                            Name = "NUnit",
                            Priority = 216,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("99f1aca2-fcf3-42be-a7c9-62c84f54b02e"),
                            IsHighlighted = false,
                            Name = "MSTest",
                            Priority = 217,
                            SkillGroup = "Backend"
                        },
                        new
                        {
                            Id = new Guid("918a79ca-a2ec-4878-9d3f-802c4bd10a64"),
                            IsHighlighted = true,
                            Name = "Angular 8+",
                            Priority = 301,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("e187b2ef-0a5d-4f5c-bd42-c288b0484bce"),
                            IsHighlighted = true,
                            Name = "Vue.js",
                            Priority = 302,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("d4f46599-5251-48f8-9097-eaee336b8993"),
                            IsHighlighted = true,
                            Name = "ASP.NET Core (Blazor)",
                            Priority = 303,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("494ed162-b23f-4ef3-a97f-3f6770ed821e"),
                            IsHighlighted = true,
                            Name = "ASP.NET",
                            Priority = 304,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("bb99c612-e5e2-43c6-a8f6-4a8bc82fa47a"),
                            IsHighlighted = true,
                            Name = "JavaScript",
                            Priority = 305,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("e73e86d9-8c82-4aa8-87f5-29007d4842a0"),
                            IsHighlighted = true,
                            Name = "TypeScript",
                            Priority = 306,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("faedd3e4-ac78-455f-a2a6-8787cc5d2724"),
                            IsHighlighted = true,
                            Name = "HTML",
                            Priority = 307,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("96eef699-0493-4389-8508-e0e5ac7a10ff"),
                            IsHighlighted = true,
                            Name = "CSS",
                            Priority = 308,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("19a964ee-362a-4f52-82c7-901ec92b190d"),
                            IsHighlighted = true,
                            Name = "WPF",
                            Priority = 309,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("4bc1fa9d-d2f2-4aa2-a3fb-1d7760106726"),
                            IsHighlighted = true,
                            Name = "XAML",
                            Priority = 310,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("3c071533-0266-4ec6-bc24-5e38f4a26bb5"),
                            IsHighlighted = false,
                            Name = "WinForms",
                            Priority = 311,
                            SkillGroup = "Frontend"
                        },
                        new
                        {
                            Id = new Guid("0f16ede3-0bc2-47b2-8a98-4b348f4b8202"),
                            IsHighlighted = true,
                            Name = "MySQL",
                            Priority = 401,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("888a9550-f2dd-4e7d-a010-bb21411ab52a"),
                            IsHighlighted = true,
                            Name = "MS SQL",
                            Priority = 402,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("2d7e5810-b437-49b5-9801-9d57b1bd0c2f"),
                            IsHighlighted = true,
                            Name = "MS SSAS",
                            Priority = 403,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("5205ec9e-f063-45cb-a587-21bca1a74892"),
                            IsHighlighted = true,
                            Name = "Cosmos DB",
                            Priority = 404,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("c7499348-ae6f-41a8-8739-92e575988976"),
                            IsHighlighted = true,
                            Name = "Dynamo DB",
                            Priority = 405,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("f2a2aa0c-46d2-4500-aae5-f85f93327eb8"),
                            IsHighlighted = true,
                            Name = "Redis",
                            Priority = 406,
                            SkillGroup = "Database"
                        },
                        new
                        {
                            Id = new Guid("014d3588-b7d8-40a9-af5e-dfc15c339c85"),
                            IsHighlighted = true,
                            Name = "Docker",
                            Priority = 501,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("f36deae8-083d-496f-8895-b3e98e7f6a96"),
                            IsHighlighted = true,
                            Name = "Kubernetes",
                            Priority = 502,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("e370472b-07c1-441f-8161-2c9ad7ed921b"),
                            IsHighlighted = true,
                            Name = "Azure DevOps",
                            Priority = 503,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("db5b7c7c-e7d7-4b4a-8462-28bbc6ce2a2c"),
                            IsHighlighted = true,
                            Name = "AWS DevOps",
                            Priority = 505,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("afee880a-2ef7-4597-b41d-faa595811aa0"),
                            IsHighlighted = true,
                            Name = "GitHub Actions",
                            Priority = 504,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("1f71b23e-6eb8-444b-945f-04dc3b6e6dcc"),
                            IsHighlighted = true,
                            Name = "Jenkins",
                            Priority = 506,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("c329e836-2e60-47ed-bcca-0e8b2b3cbef0"),
                            IsHighlighted = true,
                            Name = "TeamCity",
                            Priority = 507,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("1d205562-0906-4fa3-b410-1994000b8b91"),
                            IsHighlighted = true,
                            Name = "OKTA",
                            Priority = 508,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("e705f66c-af17-4011-b9f4-77155ca17fba"),
                            IsHighlighted = true,
                            Name = "Jira",
                            Priority = 509,
                            SkillGroup = "Tools"
                        },
                        new
                        {
                            Id = new Guid("a120ba72-3a02-47b0-b626-dc37208d0747"),
                            IsHighlighted = true,
                            Name = "Esri ArcGIS",
                            Priority = 510,
                            SkillGroup = "Tools"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillExperienceMappingSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", "Experience")
                        .WithMany("SkillExperienceMapping")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", "Skill")
                        .WithMany("SkillExperienceMapping")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Navigation("SkillExperienceMapping");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.Navigation("SkillExperienceMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
