// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeApp.DataAccess.Sql.Context;

#nullable disable

namespace ResumeApp.DataAccess.Sql.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    partial class ResumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.CertificationSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "Azure Solutions Architect Expert",
                            ResumeId = 1L,
                            VerificationUrl = "https://www.credly.com/badges/42f9be70-0b40-4bb0-8256-bd9d573e36af/public_url"
                        },
                        new
                        {
                            Id = 2L,
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Google",
                            Name = "Professional Cloud Architect",
                            ResumeId = 1L,
                            VerificationUrl = "https://www.credential.net/786961ad-0225-4bb0-883a-3c2feceb5174"
                        },
                        new
                        {
                            Id = 3L,
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Amazon",
                            Name = "AWS Certified Solutions Architect Associate",
                            ResumeId = 1L,
                            VerificationUrl = "https://www.credly.com/badges/dc95ff2a-12d8-4816-91b2-a9292ae5df85/public_url"
                        },
                        new
                        {
                            Id = 4L,
                            ExpirationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Microsoft",
                            Name = "DevOps Engineer Expert",
                            ResumeId = 1L,
                            VerificationUrl = "https://www.credly.com/badges/2d29613e-7c7e-481d-aba3-842b409fecd7/public_url"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ContactSqlEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ResumeId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Key = "Location",
                            ResumeId = 1L,
                            Value = "Sunnyvale, CA, 94085"
                        },
                        new
                        {
                            Key = "Phone",
                            ResumeId = 1L,
                            Value = "+1(408)480-3600"
                        },
                        new
                        {
                            Key = "Email",
                            ResumeId = 1L,
                            Value = "mickey.krasilnikov@gmail.com"
                        },
                        new
                        {
                            Key = "Accredible",
                            ResumeId = 1L,
                            Value = "https://www.credential.net/profile/mikhailkrasilnikov328966/wallet"
                        },
                        new
                        {
                            Key = "Credly",
                            ResumeId = 1L,
                            Value = "https://www.credly.com/users/mickey-krasilnikov/badges"
                        },
                        new
                        {
                            Key = "LinkedIn",
                            ResumeId = 1L,
                            Value = "https://www.linkedin.com/in/mickeykrasilnikov/"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.EducationSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Degree = "Bachelor's degree",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FieldOfStudy = "Design and technology of radio electronic devices",
                            Name = "Penza State University",
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://international.pnzgu.ru/"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Company = "EPAM Systems",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lead Software Engineer"
                        },
                        new
                        {
                            Id = 2L,
                            Company = "Credit Suisse",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Front Office Risk System Developer (AVP) (Senior Software Engineer)"
                        },
                        new
                        {
                            Id = 3L,
                            Company = "SINTEGRO SOFT",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = 4L,
                            Company = "Gollard",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 5L,
                            Company = "SGC",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 6L,
                            Company = "Research and Production Center 'Start'",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResumeId = 1L,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Software Engineer"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ProjectSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Envirnment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExperienceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProjectRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TaskPerformed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Client = "Broadridge",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET Core 6.0, Vue.js, Python 3.7, AWS, AWS Lambda, AWS S3, AWS Beanstalk, AWS EC2, AWS Code Commit, AWS Code Build, AWS Code Deploy, AWS Code Pipeline, Docker, AWS RDS, GIT",
                            ExperienceId = 1L,
                            ProjectRoles = "Key Developer, Team Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Client = "ElipsLife",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET Core 6.0Angular 13Go LangAzureAzure DevOpsOctopusOKTADockerCosmos DBRedisMS SQLGIT",
                            ExperienceId = 1L,
                            ProjectRoles = "Key Developer, Team Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Designed microservice-based hybrid-cloud solution architecture for multi-role self-service portal for managing insurance claims + underwriting + and broker reports.Designed and developed microservices following a RESTful approach and applying best practices. • Covered code with unit and contract tests and maintained code coverage on 80%.Configured CI/CD pipelines and established automated quality gates on different stages.Mentored new joiners and supported them during the ramp-up period.Performed systematic knowledge transfer to the client support team + including the creation of visual documentation. Introduced and ensured the development team follows the very best engineering practices (with respect to various limitations on the client side)."
                        },
                        new
                        {
                            Id = 3L,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET Core 2.1, .NET 4.6, WPF, WCF, EF, MS SQL, MS SSAS, TeamCity, Jira, Confluence, Splunk, GIT",
                            ExperienceId = 2L,
                            ProjectRoles = "Key Developer, Tech Lead",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Maintained Risk Management System for Credit Suisse Front Office and developed new modules. Improved performance and decreased memory usage in CS in-house distributed cache. Splatted monolith server-side architecture to microservices. Analyzed and arranged requirements with traders + BAU team and QA. Supported worldwide users as a part of the SL3 team. Administrated CI/CD on TeamCity. Documented design decisions and usage examples. Mentored new joiners."
                        },
                        new
                        {
                            Id = 4L,
                            Client = "Yandex",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET 4.5, ASP.NET MVC 5, ASP.NET Web API, WPF, MS SQL, EF, TFS, WIX, GIT",
                            ExperienceId = 3L,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Participated in the development of the system that helps organize corporate bonuses + such as meals + mobile phones + fitness + transportation + etc.Developed user personal page that contains account balance and transaction history. Developed desktop administration systems for corporate bonus managers.Documented design decisions + component APIs and usage examples.Participated in the software integration process."
                        },
                        new
                        {
                            Id = 5L,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET 4.5, WPF, WCF, ASP.NET Web API, Esri ArcGIS, MS SQL, MySQL, GitLab, WIX, GIT",
                            ExperienceId = 4L,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Participated in the development of desktop GIS application for the power distribution company dealing with electrical grids, stations and facilities on the map.Implemented a feature that allows monitoring the service transport on the map in real-timeIntroduced the possibility to view video streams from the cameras marked on the map.Participated in the development of the solution to maintain security and safety of the buildings and areas using cameras and different types of sensors.Implemented an alerting system that works based on the biometric data from the cameras or events from the sensors."
                        },
                        new
                        {
                            Id = 6L,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET 4.0, WPF, SOAP, MS SQL, WIX, SVN",
                            ExperienceId = 5L,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed software for composing estimates to determine the cost of construction.Integrated with other well-known systems available on the market for composing estimates."
                        },
                        new
                        {
                            Id = 7L,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Envirnment = ".NET 3.5, WinForms, SOAP, MS SQL, SVN",
                            ExperienceId = 6L,
                            ProjectRoles = "Key Developer",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskPerformed = "Developed software for designing micro boards and creating a mask for interacting with third-party equipment for printing this kind of product."
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Mikhail",
                            LastName = "Krasilnikov",
                            Summary = "12+ years of professional programming experience with consistently increasing responsibilities in the design and development of commercial applications on different platforms and environments \nCertified Cloud Solution Architect (Azure, GCP, AWS) \nExperienced as a Team Leader \nInvolved in full Software Development Life Cycle (SDLC)",
                            Title = "Lead Software Engineer"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SkillGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AdditionalInfo = ".Net Core, .Net",
                            Name = "C#",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = 2L,
                            AdditionalInfo = "Gin",
                            Name = "GoLang",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = 3L,
                            AdditionalInfo = "Node.js",
                            Name = "Javascript",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = 4L,
                            AdditionalInfo = "FastAPI",
                            Name = "Python",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Backend"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Angular",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Vue.js",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "JavaScript",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "TypeScript",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "HTML",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "CSS",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Frontend"
                        },
                        new
                        {
                            Id = 11L,
                            AdditionalInfo = "MS SQL",
                            Name = "T-SQL",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = 12L,
                            AdditionalInfo = "MySQL",
                            Name = "SQL/PSM",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = 13L,
                            AdditionalInfo = "PostgreSQL, Oracle",
                            Name = "PL-SQL",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/SQL"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "MongoDB",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Redis",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "CosmosDB",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "DynamoDB",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "BigTable",
                            ResumeId = 1L,
                            SkillGroup = "Programming Languages/Database/NoSQL"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Docker",
                            ResumeId = 1L,
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Docker Swarm",
                            ResumeId = 1L,
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Kubernetes",
                            ResumeId = 1L,
                            SkillGroup = "Container Services"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Azure DevOps",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "GitHub Actions",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "AWS CodePipeline",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Octopus",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Jenkins",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "TeamCity",
                            ResumeId = 1L,
                            SkillGroup = "CI/CD"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "JIRA",
                            ResumeId = 1L,
                            SkillGroup = "Bug Tracking"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Azure DevOps",
                            ResumeId = 1L,
                            SkillGroup = "Bug Tracking"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "GIT",
                            ResumeId = 1L,
                            SkillGroup = "Source Control"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "SVN",
                            ResumeId = 1L,
                            SkillGroup = "Source Control"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Windows",
                            ResumeId = 1L,
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "MacOS",
                            ResumeId = 1L,
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Ubuntu",
                            ResumeId = 1L,
                            SkillGroup = "OS"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Azure",
                            ResumeId = 1L,
                            SkillGroup = "Cloud"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "AWS",
                            ResumeId = 1L,
                            SkillGroup = "Cloud"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "GCP",
                            ResumeId = 1L,
                            SkillGroup = "Cloud"
                        });
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.CertificationSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Certifications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ContactSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Contacts")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.EducationSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Education")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Experience")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ProjectSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", "Experience")
                        .WithMany("Projects")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.SkillSqlEntity", b =>
                {
                    b.HasOne("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ExperienceSqlEntity", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ResumeApp.DataAccess.Sql.Entities.ResumeSqlEntity", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
